### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by ghost** [hncshp/universal-transformers-git#1]
Hi, I'm very interested in the universal transformer for translation. Recently I found this code and it's very cool!! However, when I look into this code, I found that the functions 'decoder_predict' and 'decoder_train_eval' are totally same. Is this a bug or something I ignored?

**Comment by hncshp** [comment]
hi, nice to know you. Good question! I updated my code recently, you can get the updated version. Principally speaking, the predict stage and train/eval stage have almost same decoder arch, because of the inference steps.
